language: csharp
sudo: false # faster builds
solution: ./Angular2WithAspNetCore/Angular2WithAspNetCore.sln
dist: trusty
notifications:
  email: false
cache:
  directories:
    - node_modules
before_install:
  - chmod +x build.sh
  - "npm config set spin false"
  - "npm install -g npm@^3"
  - "npm install -g gulp@^3"
  - pip install --user codecov
install:
  - dotnet restore ./Angular2WithAspNetCore/Angular2WithAspNetCore.sln
  - npm install
mono: none
dotnet: 1.0.1
script:
  - ./build.sh
after_success:
  - codecov
  - ".\Angular2WithAspNetCore\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\Angular2WithAspNetCore.Tests\bin\Debug\netcoreapp1.1\bin\Debug\Angular2WithAspNetCore.Tests.dll" 
  
